### ISSUE TITLE
Type 'ActionFactory' not found error with the latest Beta Channel 1.18.0-11.1.pre

### ISSUE THREAD

**Issue by codegrue** [stryder-dev/flutter_platform_widgets#190]
Debug Console reports: 

/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.50.0/lib/src/platform_app.dart:96:21: Error: Type 'ActionFactory' not found.
      Map<LocalKey, ActionFactory> actions,

Won't even build for Web now.

**Comment by aqwert** [comment]
you need to use the beta branch from the repo not the one in the pub.dev as that only supports the latest stable of flutter

**Comment by codegrue** [comment]
Is there a way to point to branches on GitHub from pubspec.yaml?

**Comment by aqwert** [comment]
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by Shajeel-Afzal** [comment]
@aqwert, so I guess I need to do this in the `pubspec.yaml` file:

```
dependencies:
  plugin1:
    git:
      url: git://github.com/stryder-dev/flutter_platform_widgets.git
```

However, I want to know how to specify the beta branch?

**Comment by Shajeel-Afzal** [comment]
Found the solution: 

```
flutter_platform_widgets:
    git:
      url: git://github.com/stryder-dev/flutter_platform_widgets.git
      ref: beta
```
But now I am having this problem: 

```
Compiler message:
../../../.pub-cache/git/flutter_platform_widgets-e144647d8965c581d8969078bfe16f17805fe755/lib/src/platform_button.dart:105:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
```
